# Generated by Django 4.0.1 on 2022-01-15 01:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('shop', '0001_initial')]

    initial = True

    dependencies = [
        ('miq', '0006_auto_20210908_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('position', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('position', 'name', '-created'),
            },
        ),
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('miq.page',),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('miq.image',),
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('miq.page',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('name', models.CharField(max_length=99, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('position', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category')),
                ('cover', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.productimage', verbose_name='Cover')),
                ('images', models.ManyToManyField(blank=True, related_name='products', to='shop.ProductImage')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shop_product', to='shop.productpage')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('position', '-created', 'name'),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='page',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='shop_productcategory', to='shop.categorypage'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'slug'], name='shop_produc_categor_e57932_idx'),
        ),
    ]
