# Generated by Django 3.2.2 on 2021-10-02 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='page',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='shop_category', to='shop.categorypage'),
        ),
    ]
