# Generated by Django 3.2.2 on 2021-10-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211002_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_public',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
