# Generated by Django 3.2.2 on 2021-12-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211225_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug_public',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_public',
        ),
    ]
