# Generated by Django 3.2.2 on 2021-12-29 23:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211225_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('name', models.CharField(help_text='Name', max_length=30)),
                ('value', models.CharField(help_text='Value', max_length=99)),
            ],
            options={
                'verbose_name': 'Product attribute',
                'verbose_name_plural': 'Product attributes',
                'ordering': ('created', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ('created', 'name'), 'verbose_name': 'Product size', 'verbose_name_plural': 'Product sizes'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_categor_e57932_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='color_group_pk',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Color group identifier'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_pre_sale',
            field=models.BooleanField(default=False, verbose_name='Available for pre sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_pre_sale_text',
            field=models.TextField(blank=True, null=True, verbose_name='Pre sale description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'slug', 'name'], name='shop_produc_categor_72666c_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.UniqueConstraint(fields=('product', 'name', 'code'), name='unique_product_size_name_code'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='shop.product'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_product_attribute_name'),
        ),
    ]
