# Generated by Django 3.2.2 on 2021-12-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211229_1837'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_categor_72666c_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Supplier identifier'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'slug', 'name', 'supplier_id'], name='shop_produc_categor_745ad7_idx'),
        ),
    ]
