# Generated by Django 3.2.2 on 2021-12-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211230_1338'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_categor_745ad7_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='shop_produc_name_a2070e_idx'),
        ),
    ]
