# Generated by Django 3.2.2 on 2021-12-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211230_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=99, null=True, unique=True, verbose_name='Supplier identifier'),
        ),
    ]
