# Generated by Django 3.2.2 on 2021-12-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_supplier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier_id',
            new_name='supplier_item_id',
        ),
    ]
