# Generated by Django 3.2.2 on 2022-01-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_supplier_id_product_supplier_item_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('position', '-created', 'name'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_item_category',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Supplier category'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_item_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Single item cost', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_item_cost_currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_item_url',
            field=models.URLField(blank=True, null=True, verbose_name='Supplier url'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Supplier brand name'),
        ),
    ]
