# Generated by Django 3.2.2 on 2022-01-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20220101_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_item_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Supplier url'),
        ),
    ]
