# Generated by Django 3.2.2 on 2022-01-10 21:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20220110_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 10, 21, 47, 5, 51753, tzinfo=utc), verbose_name='creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='update date and time'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
