# Generated by Django 4.0.1 on 2022-01-12 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20220110_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_pre_sale_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Availability date time'),
        ),
        migrations.AddField(
            model_name='product',
            name='stage',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual stock'), ('SUPPLIER_TRANSIT', 'Ordered from supplier'), ('INSTORE_WAREHOUSE', 'Received from supplier'), ('INSTORE_TRANSIT', 'In transit to store'), ('INSTORE', 'Available for purchase')], default='VIRTUAL', max_length=50, verbose_name='Stage'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_item_sn',
            field=models.CharField(blank=True, max_length=99, null=True, unique=True, verbose_name='Supplier item serial number'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_order_id',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Supplier order ID'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='sku',
            field=models.CharField(blank=True, max_length=99, null=True, unique=True, verbose_name='Sku'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_item_id',
            field=models.CharField(blank=True, max_length=99, null=True, unique=True, verbose_name='Supplier item identifier'),
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('order_id', models.CharField(blank=True, max_length=99, null=True, verbose_name='Order ID')),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency')),
                ('items_stage', models.CharField(choices=[('VIRTUAL', 'Virtual stock'), ('SUPPLIER_TRANSIT', 'Ordered from supplier'), ('INSTORE_WAREHOUSE', 'Received from supplier'), ('INSTORE_TRANSIT', 'In transit to store'), ('INSTORE', 'Available for purchase')], default='VIRTUAL', max_length=50, verbose_name='Stage')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('is_paid_dt', models.DateTimeField(blank=True, null=True, verbose_name='Date of payment')),
                ('is_fulfilled_dt', models.DateTimeField(blank=True, null=True, verbose_name='Date of fulfillment')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='FOB Price, excluding inbound shipping, taxes and others costs', max_digits=10, null=True)),
                ('items', models.ManyToManyField(blank=True, to='shop.Product', verbose_name='Products')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
