# Generated by Django 4.0.1 on 2022-01-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_is_pre_sale_dt_product_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stage',
            field=models.CharField(choices=[('A_VIRTUAL', 'Virtual stock'), ('B_SUPPLIER_TRANSIT', 'Ordered from supplier'), ('C_INSTORE_WAREHOUSE', 'Received from supplier'), ('D_INSTORE_TRANSIT', 'In transit to store'), ('E_INSTORE', 'Available for purchase')], default='A_VIRTUAL', max_length=50, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='items_stage',
            field=models.CharField(choices=[('A_VIRTUAL', 'Virtual stock'), ('B_SUPPLIER_TRANSIT', 'Ordered from supplier'), ('C_INSTORE_WAREHOUSE', 'Received from supplier'), ('D_INSTORE_TRANSIT', 'In transit to store'), ('E_INSTORE', 'Available for purchase')], default='A_VIRTUAL', max_length=50, verbose_name='Stage'),
        ),
    ]
