# Generated by Django 4.0.1 on 2022-01-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_supplierorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='name',
            field=models.CharField(default='New order', max_length=99, verbose_name='Name'),
        ),
    ]
